"""
演示如何通过 finquant selection 命令使用不同策略
"""

print("=" * 70)
print("finSys Selection 策略集成演示")
print("=" * 70)
print()

print("1️⃣  使用突破策略（MA Breakout Strategy）")
print("-" * 70)
print("命令:")
print("  finquant selection run \\")
print("    --config config/selection_breakout.yaml \\")
print("    --start 2023-07-01 \\")
print("    --end 2023-12-31 \\")
print("    --output-dir data/selection_breakout \\")
print("    --verbose")
print()
print("配置文件关键部分 (config/selection_breakout.yaml):")
print("  selection:")
print("    strategy_type: 'breakout'")
print("    breakout:")
print("      ma_periods: [120, 250]")
print("      volume_multiplier: 1.5")
print("      breakout_threshold: 1.05")
print()

print("2️⃣  使用因子策略（Factor-Based Strategy）")
print("-" * 70)
print("命令:")
print("  finquant selection run \\")
print("    --config config/selection_factor_based.yaml \\")
print("    --start 2023-07-01 \\")
print("    --end 2023-12-31 \\")
print("    --output-dir data/selection_factor \\")
print("    --verbose")
print()
print("配置文件关键部分 (config/selection_factor_based.yaml):")
print("  selection:")
print("    strategy_type: 'factor_based'")
print("    index_ticker: '000905.SH'")
print("    ic_window: 60")
print()

print("3️⃣  策略切换原理")
print("-" * 70)
print("CLI 内部流程:")
print("  1. 加载配置文件: config = load_config(config_path)")
print("  2. 创建策略: strategy = create_strategy(config)")
print("  3. 根据 config.selection.strategy_type 自动选择:")
print("     - 'breakout' → BreakoutStrategy")
print("     - 'factor_based' → FactorBasedStrategy")
print("  4. 执行选股: result = strategy.select(market_df, index_df, date)")
print()

print("4️⃣  输出结果")
print("-" * 70)
print("两种策略的输出格式完全相同:")
print("  - 每天一个 JSON 文件: YYYY-MM-DD_selection.json")
print("  - 包含: selected_tickers, scores, market_state 等")
print("  - 可以直接用于后续的回测和交易")
print()

print("5️⃣  向后兼容性")
print("-" * 70)
print("如果配置文件没有 strategy_type 字段:")
print("  - 默认使用 'factor_based' 策略")
print("  - 不影响现有的配置文件和工作流")
print()

print("6️⃣  验证集成")
print("-" * 70)
print("运行验证脚本:")
print("  python scripts/verify_breakout_strategy.py")
print()
print("查看配置示例:")
print("  cat config/selection_breakout.yaml")
print("  cat config/selection_factor_based.yaml")
print()

print("=" * 70)
print("✅ 策略已完全集成到 finquant selection 入口")
print("=" * 70)
